### ISSUE TITLE
[FEAT] 상품 옵션 테이블 구조 변경

### ISSUE THREAD

**Issue by isayaksh** [JSH-Kiosk/Back#9]
# ✏️ Description

## 📄 수정 전
고객이 기호에 따라 상품의 옵션을 선택할 수 있는 데이터베이스 필드를 수정한다.
기존에 상품 옵션을 관리하던 테이블 구조는 다음과 같다.

<img width="260" alt="image" src="https://github.com/JSH-Kiosk/Back/assets/85926257/dfcb5472-93d6-4e43-9bb2-5fda9fdc0c91">

기존의 테이블의 경우 `물양`에 대한 옵션에 대한 선택지가 `물 적게`, `물 적당히`, `물 많이`가 존재할 경우 아래 테이블과 같이 관리하는 구조였다.

## 📚 튜플 셋
|no|옵션(`name`)|선택지(`description`)|
|:-:|:-:|:-:|
|1|물양|물 적게|
|2|물양|물 적당히|
|3|물양|물 많이|

## 📄 수정 후

기존의 테이블은 `옵션`이라는 필드에서 중복된 값을 가지는 문제점을 발견하여 정규화를 통해 옵션(`option_category`) 테이블과 선택지(`option_selection`)로 테이블을 분리하기로 결정하였다.

<img width="601" alt="image" src="https://github.com/JSH-Kiosk/Back/assets/85926257/483fa5e5-bf2e-4662-99a9-e7f0eee5669b">

### [TABLE] 옵션 카테고리
|no|옵션명|
|:-:|:-:|
|1|물양|

### [TABLE] 옵션 선택지
|no|옵션 카테고리|옵션 선택지|
|:-:|:-:|:-:|
|1|1|물 적당히|
|2|1|물 적당히|
3|1|물 많이|

## 🤝 테이블 결과

삭제 : `item_option`, `order_item_option`
추가 : `item_option_categories`, `item_option_selections`, `order_item_option_categories`, `order_item_option_selections`

<img width="557" alt="image" src="https://github.com/JSH-Kiosk/Back/assets/85926257/5b81af52-b40c-48aa-8999-17cd34cbd689">

## ❗️ 추가사항
`item` 테이블에 `image_url` 필드가 누락되어 있는 것을 확인하고 추가 작업을 진행한다

# 🛠 TODO
### ❌ 테이블 삭제
- [ ] `item_option`
- [ ] `order_item_option`

### 📌 테이블 추가
- [ ] `item_option_categories`
- [ ] `item_option_selections` 
- [ ] `order_item_option_categories`
- [ ] `order_item_option_selections`

### ✍️ 테이블 수정
- [ ] `items`
